/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    public static int timesFive(int n) {
    	return n*5;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(timesFive(3));
    }
}
